var firstName = prompt("What is your first name?")
var lastName = prompt("What is your last name?")
var age = prompt("How old are you?")
alert("Hello " + firstName + " " + lastName + "!" + " You are " + age + " years old!")
console.log("Your full name is " + firstName + " " + lastName + ", you are " + age + " years old.")
